spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/fynd_db?useSSL=false&serverTimezone=UTC
    username: root
    password: root22!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # update, create, create-drop, validate selon l'environnement
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect